<template>
	<nav class="menu-wrapper">
		<button class="hamburger hamburger--squeeze" v-bind:class="[isActive ? 'is-active' : '']" type="button" @click.prevent="isActive = !isActive">
			<span class="hamburger-box">
				<span class="hamburger-inner"></span>
			</span>
		</button>

		<transition name="menu-fadein">
			<ul class="menu-dropdown direction-left" v-if="isActive">
				<slot></slot>
			</ul>
		</transition>

	</nav>
</template>

<script>


	export default {

		props: ['href', 'direction'],

		data: function () {
			return {
				isActive : false,
			}
		},


		watch: {
			isActive(isActive) {
				if (isActive) {
					document.addEventListener('keyup', this.listenForClose);
					document.addEventListener('click', this.listenForClose);
				}
				else {
					document.removeEventListener('keyup', this.listenForClose);
					document.removeEventListener('click', this.listenForClose);
				}
			},
		},


		methods: {
			listenForClose(event) {
				if (event.type == 'keyup' && event.key == 'Escape') {
					this.isActive = false;
				}

				if (event.type == 'click') {
					if (!event.target.closest('.menu-wrapper')) {
						this.isActive = false;
					}
				}
			},
		},
	}
</script>


<style>

.menu-wrapper {position:relative;}

.menu-dropdown {position:absolute; width:180px; padding:0.5em 0; border-radius: 0.3em; z-index:999}
.menu-dropdown {background:#1d5282;}
.menu-dropdown.direction-left {right:0.5em; top:2.5em; text-align:center;}

.menu-dropdown li {display:block; width:100%;}



/* ----------------------------------------------
 * Generated by Animista on 2019-9-15 22:18:13
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

.menu-fadein-enter-active { animation: swing-in-top-fwd 0.2s cubic-bezier(0.175, 0.885, 0.320, 1.275) both;}
/* .menu-fadein-leave-active {animation: swing-out-top-bck 0.1s cubic-bezier(0.600, -0.280, 0.735, 0.045) both;} */

.menu-fadein-leave-active {animation: swirl-out-bck 0.25s ease-in both;}

@keyframes swing-in-top-fwd {
  0% {
    transform: rotateX(-100deg);
    transform-origin: top;
    opacity: 0;
  }
  100% {
    transform: rotateX(0deg);
    transform-origin: top;
    opacity: 1;
  }
}

/*
@keyframes swing-out-top-bck {
  0% {
    transform: rotateX(0deg);
    transform-origin: top;
    opacity: 1;
  }
  100% {
    transform: rotateX(-100deg);
    transform-origin: top;
    opacity: 0;
  }
}
*/

@keyframes swirl-out-bck {
  0% {
    transform: rotate(0) scale(1);
    opacity: 1;
  }
  100% {
    transform: rotate(-540deg) scale(0);
    opacity: 0;
  }
}

/*!
 * Hamburgers
 * @description Tasty CSS-animated hamburgers
 * @author Jonathan Suh @jonsuh
 * @site https://jonsuh.com/hamburgers
 * @link https://github.com/jonsuh/hamburgers
 */
.hamburger {
padding: 5px 10px; border: 0; margin: 0;
display: inline-block; cursor: pointer; transition-property: opacity, filter; transition-duration: 0.15s; transition-timing-function: linear;
font: inherit; color: inherit; text-transform: none; background-color: transparent; overflow: visible; }
.hamburger:hover {background-color:var(--highlight);}
.hamburger-box { width: 1.25em; display: inline-block; position: relative; }

.hamburger-inner { display: block; top: 50%; margin-top: -8px; }
.hamburger-inner, .hamburger-inner::before, .hamburger-inner::after {
width: 1.25em; height: 2px; border-radius: 2px; background-color: #fff;position: absolute;
transition-property: transform; transition-duration: 0.15s; transition-timing-function: ease; }
.hamburger-inner::before, .hamburger-inner::after { content: ""; display: block; }
.hamburger-inner::before { top: -8px; }
.hamburger-inner::after { bottom: -8px; }

.hamburger--squeeze .hamburger-inner { transition-duration: 0.075s; transition-timing-function: cubic-bezier(0.55, 0.055, 0.675, 0.19); }
.hamburger--squeeze .hamburger-inner::before { transition: top 0.075s 0.12s ease, opacity 0.075s ease; }
.hamburger--squeeze .hamburger-inner::after { transition: bottom 0.075s 0.12s ease, transform 0.075s cubic-bezier(0.55, 0.055, 0.675, 0.19); }

.hamburger--squeeze.is-active .hamburger-inner {
transform: rotate(45deg); transition-delay: 0.12s; transition-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1); }
.hamburger--squeeze.is-active .hamburger-inner::before { top: 0; opacity: 0; transition: top 0.075s ease, opacity 0.075s 0.12s ease; }
.hamburger--squeeze.is-active .hamburger-inner::after {
bottom: 0; transform: rotate(-90deg); transition: bottom 0.075s ease, transform 0.075s 0.12s cubic-bezier(0.215, 0.61, 0.355, 1); }
</style>